import Link from "next/link";

export const ItemsSpecify = () => {
    return (
        <div
            className="
            flex 
            justify-center 
            mt-5 
            md:w-full 
            md:mt-10"
        >
            <div
                className="
                hidden 
                gap-x-12 
                mx-3 
                gap-4 
                md:grid
                grid-cols-3 
                grid-rows-2
                md:gap-x-28 
                md:gap-y-8
                xl:flex 
                xl:gap-20
                2xl:flex 
                2xl:gap-x-40"
            >
                <Link
                    href="/livros"
                    className="
                        bg-purple-600 
                        flex 
                        flex-col 
                        rounded-full 
                        p-3 
                        items-center 
                        md:p-3 
                        lg:rounded-3xl 
                        cursor-pointer 
                        flex-grow 
                        shadow-lg 
                        shadow-indigo-500/50
                        hover:scale-110"
                >
                    <img
                        src="https://www.shutterstock.com/image-vector/book-icon-sign-design-600nw-553945819.jpg"
                        className="
                        w-16 
                        h-16 
                        rounded-[50%]
                        md:w-20 
                        md:h-20
                        lg:w-32 
                        lg:h-32"
                    />
                    <p
                        className="
                            hidden 
                            lg:block
                            font-serif 
                            text-slate-600 
                            md:text-black 
                            ml-3 
                            md:ml-0 
                            text-sm 
                            md:text-lg 
                            xl:text-xl 
                            md:text-center 
                            mt-2"
                    >Livros
                    </p>
                </Link>

                <Link
                    href={'/eletrodomesticos'}
                    className="
                            bg-purple-600 
                            flex 
                            flex-col 
                            rounded-full 
                            pt-3 
                            items-center 
                            md:p-3 
                            lg:rounded-3xl 
                            cursor-pointer 
                            flex-grow
                            shadow-lg 
                            shadow-indigo-500/50
                            hover:scale-110"
                >
                    <img
                        src="https://img.freepik.com/vetores-premium/icone-de-vetor-de-geladeira-em-um-fundo-branco_855620-184.jpg"
                        className="
                            w-16 
                            h-16 
                            rounded-[50%] 
                            bg-purple-600
                            md:w-20 
                            md:h-20
                            lg:w-32 
                            lg:h-32"
                    />
                    <p
                        className="
                            hidden 
                            lg:block
                            font-serif 
                            text-slate-600 
                            md:text-black 
                            text-sm 
                            md:text-lg 
                            xl:text-xl 
                            md:text-center 
                            mt-2"
                    >
                        Elétrodomésticos
                    </p>
                </Link>

                <Link
                    href={'/promocoes'}
                    className="
                        bg-purple-600 
                        flex 
                        flex-col 
                        rounded-full 
                        pt-3 
                        items-center 
                        md:p-3 
                        lg:rounded-3xl 
                        cursor-pointer 
                        flex-grow
                        shadow-lg 
                        shadow-indigo-500/50
                        hover:scale-110"
                >
                    <img
                        src="https://static.vecteezy.com/ti/vetor-gratis/p1/18813321-icone-do-smartphone-telefone-em-tela-cheia-celular-fundo-branco-celular-preto-e-branco-transparente-handphone-em-tela-cheia-de-de-icone-vetor.jpg"
                        className="
                            w-16 
                            h-16 
                            rounded-[50%] 
                            bg-purple-600
                            md:w-20 
                            md:h-20
                            lg:w-32 
                            lg:h-32"
                    />
                    <p
                        className="
                            hidden
                            lg:block
                            font-serif 
                            text-slate-600 
                            md:text-black 
                            text-sm md:text-lg 
                            xl:text-xl 
                            md:text-center 
                            mt-2"
                    >
                        Promoções
                    </p>
                </Link>
            </div>
        </div>
    );
}