export const products = [
    {
        id: 1,
        name: 'Pai Rico, Pai Pobre - Edição de 20 Anos Atualizada e Ampliada',
        description: 'Celebrando 20 anos como o livro n° 1 em finanças pessoais. A escola prepara as crianças para o mundo real? Essa é a primeira pergunta com a qual o leitor se depara neste livro. O recado é ousado e direto: boa formação e notas altas ...',
        review: 4,
        price: 35.54,
        category: "livros",
        carouselCategory: "bestSellersCarousel",
        quantity: 1,
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRXFWH8oRwmvaMPb-u7FbRlYLbgWRVko5Mru_ln2XKoERZIpsFmqsORskovInBoaTLafg2xa5aohwkQx6Hdi-Tqm_bVeHL_giu_YbfcSxPB&usqp=CAE"
    },
    {
        id: 2,
        name: 'Ultra-aprendizado: Domine habilidades valiosas, seja mais esperto que a competição',
        description: 'Quem você pode se tornar se adotar a abordagem certa para ser bem-sucedido? Conheça a estratégia de aquisição de habilidades e conhecimento que vai impulsionar sua carreira e te ajudar a alcançar qualquer objetivo. Pratique o melhor jeito de aprender com Ultra-aprendizado .',
        review: 4,
        price: 63.99,
        category: "livros",
        carouselCategory: "bestSellersCarousel",
        quantity: 1,
        image: "https://livrariaflorence.fbitsstatic.net/img/p/livro-ultra-aprendizado-young-218173/404524.jpg?w=660&h=660&v=no-change&qs=ignore"
    },
    {
        id: 3,
        name: 'A revolução dos bichos',
        description: 'A REVOLUÇÃO DOS BICHOS foi considerado pela revista Times um dos 100 melhores da língua inglesa. Esta fábula narra a insurreição dos animais de uma fazenda contra seus donos, em busca de uma vida mais livre e igualitária',
        review: 4,
        price: 46.99,
        category: "livros",
        carouselCategory: "bestSellersCarousel",
        quantity: 1,
        image: "https://cirandacultural.fbitsstatic.net/img/p/a-revolucao-dos-bichos-70717/257231.jpg?w=520&h=520&v=no-change&qs=ignore"
    },
    {
        id: 4,
        name: 'E assim que começa (Vol. 2 É assim que acaba)',
        description: 'Preparem os corações. Lily e Atlas estão de volta na aguardada sequência de É assim que acaba. É assim que começa chega para consagrar novamente Colleen Hoover como a autora mais vendida do Brasil...',
        review: 4,
        price: 68.99,
        category: "livros",
        carouselCategory: "bestSellersCarousel",
        quantity: 1,
        image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTN9FAL3QKFOrx3O7FQLXJF8NGZgENnLwNM7Tiz6K1IKRskD5eMrt_igcAgFUPfL8A6RVgVbjNtfHlebiY_FRJ6M6RYBNFttTf27EUwhoa9&usqp=CAE"
    },
    {
        id: 5,
        name: 'Os sete maridos de Evelyn Hugo',
        description: 'Com todo o esplendor que só a Hollywood do século passado pode oferecer, esta é uma narrativa inesquecível sobre os sacrifícios que fazemos por amor, o perigo dos segredos e o preço da fama...',
        review: 4,
        price: 39.99,
        category: "livros",
        carouselCategory: "bestSellersCarousel",
        quantity: 1,
        image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQVJVlM17aJ9H39xhWhuQna1OdIimS_XY27yZ2he3x--FWj5TGni9hs-IphRw5JlXwK7VaMxGYaAkdDfcnA_czLHVxI86jBbj5iVVo2jXWpMFtDO6YX_gov&usqp=CAE"
    },
    {
        id: 6,
        name: 'Todas as suas (im)perfeições',
        description: 'Uma história de amor perfeita é suficiente para manter vivo o casamento entre duas pessoas imperfeitas? Quando a dança começa, a sincronia é perfeita, os passos seguem o ritmo, as mãos não se soltam, os olhos jamais se deixam. Mas a música pode acabar a qualquer momento...',
        review: 4,
        price: 48.99,
        category: "livros",
        carouselCategory: "bestSellersCarousel",
        quantity: 1,
        image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTyHxA0yFHA1k8HrWrF-oHIVSPc4u1Q4haXss-olSGywTO5OhLJ7ynmQlNMCiBpM2gGz_rfWG7ZL12eHscsxIXnEWSf2ZPesJ4GYpK_24A&usqp=CAE"
    },
    {
        id: 7,
        name: 'O labirinto dos desgarrados, O Ocidente e seus adversários',
        description: 'Uma guerra devasta o coração da Europa, reacendendo os piores traumas do passado. A ameaça de um cataclismo nuclear não cessa de aumentar, precisamente quando se pensava que esse perigo havia sido afastado. Está em curso um confronto mundial que coloca o Ocidente contra a China e a Rússia...',
        review: 4,
        price: 68.99,
        category: "livros",
        carouselCategory: "newBooks",
        quantity: 1,
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTVD1s31PcOqes0fHn9sHTsOOH-7O5MJzQY04oAZALawknTmuIO"
    },
    {
        id: 8,
        name: 'A filha cubana, Sete filhas. Sete segredos. Sete amores',
        description: 'Um mistério adormecido há setenta anos. Uma escolha dilacerante: manter-se leal à família ou seguir o coração?',
        review: 4,
        price: 32.99,
        category: "livros",
        carouselCategory: "newBooks",
        quantity: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSu13z-V4OyHTci-tcm-cn87vN94IIOWxbmMBTPGm5WguUve-_O"
    },
    {
        id: 9,
        name: 'Babel Ou a necessidade de violência',
        description: 'Em 1828, um menino se torna órfão pelo rastro do cólera em Cantão, na China. Sob o nome de Robin Swift, ele é levado a Londres pelo misterioso professor Lovell e por anos se dedica ao estudo de diversos idiomas, como latim e grego antigo, preparando-se para um dia ingressar no prestigiado Real Instituto de Tradução da Universidade de Oxford, conhecido como Babel.',
        review: 4,
        price: 57.99,
        category: "livros",
        carouselCategory: "newBooks",
        quantity: 1,
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTe6Bdr47AZZBxl0uikEFQ76wUECOTyesqtgId65HoXK6hvnPtp"
    },
    {
        id: 10,
        name: 'Princesa dos ladrões',
        description: 'Uma mulher é muitas coisas e, às vezes, as impressões a respeito dela podem ser antagônicas. A srta. Adelaide Frampton é um claro exemplo disso. Ao norte de Londres, em Mayfair, todos julgam que é a prima sem graça da Duquesa de Trevescan...',
        review: 4,
        price: 45.99,
        category: "livros",
        carouselCategory: "newBooks",
        quantity: 1,
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSUCgCpP08R_QcM7XH5w8xJQTzf_QhKoLziBupEiKdq4f3w48Xk"
    },
    {
        id: 11,
        name: 'Meu sol de primavera',
        description: 'Chér vive aos 15 anos uma paixão intensa por um colega de classe. Sonha dar o primeiro beijo, ser pedida em namoro e viver um lindo romance. Quando surge uma oportunidade de fisgar o garoto, Chér não hesita em bolar um plano para conquistar o coração do crush. Será que seus planos darão certo? Ela conseguirá viver o romance tão desejado?',
        review: 4,
        price: 50.99,
        category: "livros",
        carouselCategory: "newBooks",
        quantity: 1,
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRAB9mvAw568dOvsWEBeKAWfQETvNDkH69unTAfMPPErQ0NO-gB"
    },
    {
        id: 12,
        name: 'A serpente e as asas feitas de noite, Livro 1 da duologia Nascidos da Noite',
        description: 'Para humanos e vampiros, as regras são as mesmas: nunca confie em ninguém, nunca ceda e sempre — sempre — proteja seu coração. A serpente e as asas feitas de noite é sucesso no TikTok e o primeiro volume da duologia Nascidos da noite, a saga inicial de Coroas de Nyaxia, uma romantasia repleta de magia das sombras, intrigas e romances perigosos.',
        review: 4,
        price: 36.99,
        category: "livros",
        carouselCategory: "newBooks",
        quantity: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRRd5S-umrcf_SYcMaGSHChoTtUPGYlqBtQxH9erFWDt6HlSFw"
    },
    {
        id: 13,
        name: "Fogao 6 Bocas Acendimento Automático Bivolt Waves Itatiaia",
        description: 'Resistência e facilidade a favor da agilidade na cozinha. Cozimento mais rápido com durabilidade, queimadores em alumínio robustos, acendimento automático, pés altos e resistentes. Selo conpet de eficiência energética forno easyclean, luz no forno com lâmpada blindada e porta do forno com dobradiça multi estágio.',
        review: 4,
        price: 659.99,
        category: 'eletrodomesticos',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://img.freepik.com/fotos-premium/fogao-a-gas-sobre-o-fundo-branco_739536-3231.jpg'
    },
    {
        id: 14,
        name: "Geladeira/Refrigerador Frost Free cor Inox 310L Electrolux (TF39S)",
        description: 'A geladeira Electrolux Cycle Defrost DC35A possui um design único e moderno, com puxador ergonômico e integrado, que é embutido e super fácil de limpar. O modelo é duplex, com degelo manual na cor branca, que combina com qualquer cozinha.',
        review: 4,
        price: 1299.00,
        category: 'eletrodomesticos',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://brastemp.vtexassets.com/arquivos/ids/223710/Imagem-1_0.jpg?v=637699029189470000'
    },
    {
        id: 15,
        name: 'Panela Eletrica de Arroz PH5P Visor Glass Philco',
        description: 'A Panela Elétrica de Arroz PH5P Visor Glass é muito prática, conta com tigela com revestimento antiaderente e capacidade para 5 xícaras de arroz. A função Refogar/Cozinhar permite refogar alimentos antes de cozinhar. Prepare diversas receitas como: ensopados, sopas, legumes e muito mais.',
        review: 4,
        price: 179.99,
        category: 'eletrodomesticos',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTrDTDrOqzcdvMy4iTIXEDV7iHy6qZF-Yt-rdUxUd7kpLuRZX5dAvSoUujU7PPxKCly8XFEON7u5AyTXfMhXwwrIVOgtE9B8qiOrlCvlug&usqp=CAE'
    },
    {
        id: 16,
        name: 'Micro-ondas Mondial 21L Preto MO-01-21-Bl',
        description: 'Tudo ao seu alcance! Com o painel do seu mais novo micro-ondas, você poderá preparar suas receitas preferidas de forma rápida e fácil, pois ele conta com Menu Dia a Dia, que são receitas utilizadas com mais frequência. O Micro-ondas da Mondial foi desenvolvido também para lugares com pouco espaço, sendo um produto leve e compacto, que pode ser posicionado em bancadas, torre quente e muitos outros locais.',
        review: 4,
        price: 437.99,
        category: 'eletrodomesticos',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://fujioka.vteximg.com.br/arquivos/ids/183669-1000-1000/a_196642_01.png?v=637680843339370000'
    },
    {
        id: 17,
        name: 'Fritadeira Sem Oleo Air fryer eos Chef Gourmet 4 Litros Preto com Cinza EAF40S 110V',
        description: 'A Air Fryer eos 4 Litros é uma opção prática e eficiente para cozinhar. Com capacidade interna de 4 litros, é ideal para porções generosas. Possui tecnologia Turbo Twist AirFryer para um cozimento mais rápido, sistema antiaderente M...',
        review: 4,
        price: 330.86,
        category: 'eletrodomesticos',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQhOSkRr8NMNQdoFECtjXffQkm2aVpL32DchlzpdqVgjSUHQ8W0NAVIKfzvlZUwyjDBjlKI-ofwI-4N_tm3EwkSqCKgfVQf82-5kWZO-CGtFlgUfqfLBeJF&usqp=CAE'
    },
    {
        id: 18,
        name: 'Relogio Inteligente Smartwatch W34 S Preto Android Ios',
        description: 'O Relógio Smartwatch Masculino e Feminino NFC S8 Ultra Pro Max é o acessório perfeito para quem busca estilo e funcionalidade. Com um design elegante e moderno, sua caixa em metal inoxidável na cor preto/cinza possui um tamanho de 49 mm, garantindo uma tela ampla de 49 mm para uma experiência visual incrível.',
        review: 4,
        price: 79.76,
        category: 'promocoes',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS_RUGt_1nIAs2_3eg9qOKVotZTAam2iIBQiQFDfDBp4rlCDXSthDb2NjqnrXJfcQSxmfNVrpEqythV7tnpKqKQdaW5qa0Vdkmz8bA-LvqOkLE-Y2j8qAQkYw&usqp=CAE'
    },
    {
        id: 19,
        name: 'Aparador De Cabelo Profissional Elétrico T9 Barbeador Barba 0mm Máquina De Corte Para Homens Recarregável',
        description: 'Aprecie o estilo tradicional com a Máquina de Aparador de Cabelo Profissional T9! Este aparador elétrico é perfeito para os homens que valorizam um corte de cabelo impecável, oferecendo uma experiência de barbear inigualável.',
        review: 4,
        price: 39.57,
        category: 'promocoes',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcR_OTqM0K9B8qGWAQl9kDxv3Fs7UQN7nTKH7tfS8sccfOg7mpo3gGYr3QFhGnxH6EbgcsQp7g3dcbBd4xeHeNCCVeNUEFev98TCtDVw_YtC&usqp=CAE'
    },
    {
        id: 20,
        name: 'Fone De Ouvido Sem Fio Bluetooth l12 Tws Touch Recarregável',
        description: 'Ao ser in-ear, melhoram a qualidade do áudio e são de tamanho pequeno para que possam ser inseridos em sua orelha. Eles são ideais para acompanhar você quando se exercita enquanto se adentra no melhor som envolvente.',
        review: 4,
        price: 59.99,
        category: 'promocoes',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRMrQPiPQj62PKKrG9h4JEV2h33wlHFFQ6qcbmvQFi8K9-_1f5yMfV3bG-49JxZEtkh1FQwH0If-a0f-9kecjILj65XX3CmI2EFr7ZZhe5DKwNkt4Fo8lpc7Q&usqp=CAE'
    },
    {
        id: 21,
        name: 'Relogio Casio Collection Masculino MTP-V006D-7BUDF',
        description: 'Se você tem dificuldade em chegar no horário para trabalhar, costuma perder seus programas favoritos ou se atrasar para aquele encontro que você tanto aguardava, ou mesmo quer incrementar seu visual com um acessório, o ideal é ter um relógio, que além de deixar o seu dia a dia mais prático e pontual, também traz elegância no seu uso. O relógio MTP-V002D-1BUDF da Casio masculino é do tipo analógico, e para te deixar mais elegante ele vem com uma pulseira na cor prata',
        review: 4,
        price: 249.90,
        category: 'promocoes',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTijrtvVXrS2dGuAKZwTy5s1Zd1yeLF5cJgdwSq57xy2znjq8WopYSv4F94Et0H2F15vUCMahQDdAzVPgxs50SK9yXFvVqWxr5-6lGys7M&usqp=CAE'
    },
    {
        id: 22,
        name: 'Caixa De Som Bluetooth JBL Original',
        description: 'alto-falante bluetooth 60w potência de saída alto-falante bluetooth com amplificador classe d excelente baixo performace alto-falante de alta fidelidade. - a90 bluetooth speaker bluetooth 5.0 garante o emparelhamento imediato. Os alto-falantes sem fio têm velocidades de conexão mais rápidas, transmissão de sinal mais estável e menor consumo de energia. Conecte facilmente telefones celulares, computadores e etc..',
        review: 4,
        price: 480.99,
        category: 'promocoes',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTbbaZvjFtnd0iODRtWeuzGtrzoPc0U7FfgEVKWASi32rrk2OaVa6YbajNbI6zQtgMkdi6vt7RfGY-j3K4aq0wutb_kSHIi65A2g0Lhe0XbN_n8sGbBdENB&usqp=CAE'
    },
    {
        id: 23,
        name: 'Lanterna tactica recarregável Genérica Xml T9 cor preto',
        description: 'Obtenha a lanterna ideal para todas as suas necessidades. Feita com materiais resistentes e de qualidade, ela se adapta a todas as situações em que você precise de uma boa iluminação.',
        review: 4,
        price: 83.50,
        category: 'promocoes',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRgN0Sc_Ut8xxYHhcfynXP0ZaRT8vfYIDVZQeUFhMBDbvrcQSu-X5YJYgEjE_uslxLMhfzbFZShmc4pZKZHPypfIXGxKmzi-OFZOOYuxc27HR19Jw1mzDvDRg&usqp=CAE'
    },
    {
        id: 24,
        name: 'Tenis Olympikus Feminino 146G Ultraleve/148 Corrida',
        description: 'Supere seus limites para ir mais longe com o Tênis Olympikus 146G Ultraleve Feminino. Com um design moderno, o tênis running possui cabedal em formato de meia que oferece fácil calce e é extremamente leve e flexível, através da tecnologia HYPERSOX',
        review: 4,
        price: 130.54,
        category: 'promocoes',
        carouselCategory: "HomeAppliences",
        quantity: 1,
        image: 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTHCMgMhPBH9rCId5anmDwlf_Cl5irgq1YDOJ5559TVjFCTVSUyR3RD5RxD77GiyEcb43JqitLwzkp870Sa2NMV6bflyk_YEh2hQ35f1SrFq5ImwO4rHd--&usqp=CAE'
    },
];

